name: Remote Bazel cache MacOS

on:
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - namespace-profile-macos

        folder:
          - "bufbuild"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bazel cache
        run: |
          nsc version

          nsc bazel cache setup --bazelrc=/tmp/bazel-cache.bazelrc

      - name: bazel test //...
        working-directory: ${{ matrix.folder }}
        run: |
          bazel --bazelrc=/tmp/bazel-cache.bazelrcFIG test //...
